import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import {
  defaultProductConfig,
  writeProjectManifest,
  writeWorkspaceConfig,
} from "./config.js";
import { pathExists } from "./fs-utils.js";
import { DEFAULT_HOST, DEFAULT_PRESET } from "./types.js";

export async function runInit(cwd: string, preset: string): Promise<string[]> {
  if (preset !== DEFAULT_PRESET) {
    throw new Error(`unsupported preset: ${preset} (supported: ${DEFAULT_PRESET})`);
  }

  const written: string[] = [];
  const product = defaultProductConfig(preset);

  const configPath = await writeWorkspaceConfig(cwd, product);
  written.push(path.relative(cwd, configPath) || path.basename(configPath));

  const manifestPath = await writeProjectManifest(cwd, {
    targets: ["web"],
    tooling: ["vite"],
  });
  written.push(path.relative(cwd, manifestPath) || path.basename(manifestPath));

  const hostEntry = path.join(cwd, DEFAULT_HOST.entry);
  if (!(await pathExists(hostEntry))) {
    await mkdir(path.dirname(hostEntry), { recursive: true });
    await writeFile(
      hostEntry,
      `// Host entry stub generated by @client-platform/microfrontend\nexport function mountHost(root: HTMLElement): void {\n  root.textContent = "microfrontend host";\n}\n`,
      "utf8",
    );
    written.push(path.relative(cwd, hostEntry));
  }

  return written;
}
